"""case main menu fields and reference counter

Revision ID: 57c827bce15b
Revises: 45f401bc2960
Create Date: 2026-03-18 14:05:45.220682

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '57c827bce15b'
down_revision = '45f401bc2960'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_reference_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('case', sa.Column('client_name', sa.String(length=300), nullable=True))
    op.add_column('case', sa.Column('fee_earner_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'case', 'user', ['fee_earner_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'case', type_='foreignkey')
    op.drop_column('case', 'fee_earner_user_id')
    op.drop_column('case', 'client_name')
    op.drop_table('case_reference_counter')
    # ### end Alembic commands ###

