"""add file folder path and pinning

Revision ID: b6a2e5ce9f3b
Revises: fb0f9dfd6e9f
Create Date: 2026-03-19
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "b6a2e5ce9f3b"
down_revision = "fb0f9dfd6e9f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("folder_path", sa.Text(), nullable=False, server_default=""))
    op.add_column(
        "file",
        sa.Column("is_pinned", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "is_pinned")
    op.drop_column("file", "folder_path")
    # ### end Alembic commands ###

