"""add case access rules

Revision ID: fb0f9dfd6e9f
Revises: a64dcf2a4f88
Create Date: 2026-03-18 12:47:09.379517

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = 'fb0f9dfd6e9f'
down_revision = 'a64dcf2a4f88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_access_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('allow', 'deny', name='case_access_mode'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_access_rule')
    # ### end Alembic commands ###

